name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: yarn install, build
      run: |
        yarn
        yarn run build
    - name: Release Github Pages
      uses: igolopolosov/github-action-releasegithub-pages@master
